// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzdhIVEM2Fw_cxQ9ujY0QOWuuaqUCN-U',
    appId: '1:184070457722:web:34466193c221b2b9adaec3',
    messagingSenderId: '184070457722',
    projectId: 'fir-basics-tutorial-f8379',
    authDomain: 'fir-basics-tutorial-f8379.firebaseapp.com',
    storageBucket: 'fir-basics-tutorial-f8379.firebasestorage.app',
    measurementId: 'G-W3QFHE24GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ajDEHEZ7_ZKrlgBFTm94CTxQaGla_yc',
    appId: '1:184070457722:android:d66f9398a8793300adaec3',
    messagingSenderId: '184070457722',
    projectId: 'fir-basics-tutorial-f8379',
    storageBucket: 'fir-basics-tutorial-f8379.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClXp1-kG9Pmx_K2NZDTj0GyLzZDB-UaAI',
    appId: '1:184070457722:ios:0cedbb94d3e1cecbadaec3',
    messagingSenderId: '184070457722',
    projectId: 'fir-basics-tutorial-f8379',
    storageBucket: 'fir-basics-tutorial-f8379.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBasicsTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClXp1-kG9Pmx_K2NZDTj0GyLzZDB-UaAI',
    appId: '1:184070457722:ios:0cedbb94d3e1cecbadaec3',
    messagingSenderId: '184070457722',
    projectId: 'fir-basics-tutorial-f8379',
    storageBucket: 'fir-basics-tutorial-f8379.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBasicsTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANzdhIVEM2Fw_cxQ9ujY0QOWuuaqUCN-U',
    appId: '1:184070457722:web:186a5455739f0a66adaec3',
    messagingSenderId: '184070457722',
    projectId: 'fir-basics-tutorial-f8379',
    authDomain: 'fir-basics-tutorial-f8379.firebaseapp.com',
    storageBucket: 'fir-basics-tutorial-f8379.firebasestorage.app',
    measurementId: 'G-ZN19PDNLW4',
  );
}
